on: [push]
jobs: 
  BuildPlugin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: gradle build
    
      - uses: actions/upload-artifact@v3
        with:
          name: plugin
          path: build/libs/exam2022-1.0.jar
